/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.newgui;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author NTV
 */
public class test extends javax.swing.JFrame {

    QLKMFrm ql;
    LichSuGDFrm qltk;
    QLGiaoCaFrm frmGiaoCa;
    ThongKeFrm frmThongKe;
    QLSPFrm qlSPFrm;
    QLKhachHangFrm qlKH;
    /**
     * Creates new form test
     */
    public test() {
        initComponents();
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
//        this.setAlwaysOnTop(true);
        //chạy giao ca
//        if (frmGiaoCa == null || frmGiaoCa.isClosed()) {
//            frmGiaoCa = new QLGiaoCaFrm();
//            jDesktopPane1.add(frmGiaoCa);
//            frmGiaoCa.setVisible(true);
//        } else {
//            frmGiaoCa.setVisible(true);
//        }
        // Chạy thống kê
//        if (frmThongKe == null || frmThongKe.isClosed()) {
//            frmThongKe = new ThongKeFrm(jDesktopPane1);
//            jDesktopPane1.add(frmThongKe);
//            frmThongKe.setVisible(true);
//        } else {
//            frmThongKe.setVisible(true);
//        }
//          Chạy QLSP
//        if (qlSPFrm == null || qlSPFrm.isClosed()) {
//            qlSPFrm = new QLSPFrm(null);
//            jDesktopPane1.add(qlSPFrm);
//            qlSPFrm.setVisible(true);
//        } else {
//            qlSPFrm.setVisible(true);
//        }
        //          Chạy QLKH
        if (qlKH == null || qlKH.isClosed()) {
            qlKH = new QLKhachHangFrm();
            jDesktopPane1.add(qlKH);
            qlKH.setVisible(true);
        } else {
            qlKH.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout());

        jDesktopPane1.setLayout(new java.awt.GridLayout());
        getContentPane().add(jDesktopPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    // End of variables declaration//GEN-END:variables
}
