/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package poly.gui;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.sql.Connection;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.table.DefaultTableModel;
import poly.dao.DanhMucDao;
import poly.dao.KhuyenMaiDAO;
import poly.dao.SanPhamDao;
import poly.entity.KhuyenMai;
import poly.entity.SanPham;
import poly.entity.DanhMuc;
import poly.helper.Messeger;
import poly.helper.XDate;
import poly.helper.XValidate;

/**
 *
 * @author 98tae
 */
public class QL_KhuyenMaiJDiaLog extends javax.swing.JDialog {

    /**
     * Creates new form QL_KhuyenMaiJDiaLog
     *
     * @param parent
     * @param modal
     */
    KhuyenMaiDAO kmDao;
    DanhMucDao dmDao;
    SanPhamDao spDao;
    DefaultTableModel model_tbl;
    DefaultTableModel model_tbl_HetHan;
    DefaultTableModel model_tbl_HoaDon;
    DefaultTableModel model_tbl_HoaDonHetHan;
    DefaultComboBoxModel<SanPham> modelcbb_sp;
    DefaultComboBoxModel<DanhMuc> modelcbb_dm;
    CardLayout card_radio;
    CardLayout card_tbl;
    CardLayout card_tbl_hoadon;
    DefaultComboBoxModel<SanPham> model_sp;
    DefaultComboBoxModel<DanhMuc> model_dm;

    public QL_KhuyenMaiJDiaLog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtKhuyenMai = new javax.swing.JTextField();
        txtGiaTri = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNgayBatDau = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtNgayKetThuc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtGiamToiDa = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTenKhuyenMai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        radiovnd = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        radioPT = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        radioDanhMuc = new javax.swing.JRadioButton();
        radioSanPham = new javax.swing.JRadioButton();
        jpnCardgoc = new javax.swing.JPanel();
        jpnSP = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cbbSP = new javax.swing.JComboBox<>();
        jpnDM = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        cbbDanhMuc = new javax.swing.JComboBox<>();
        radio_AD_HoaDon = new javax.swing.JRadioButton();
        radio_AD_SanPham = new javax.swing.JRadioButton();
        jlbadkm = new javax.swing.JLabel();
        jlbhdtt = new javax.swing.JLabel();
        txthdtoithieu = new javax.swing.JTextField();
        jpncardGoctbl = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblhethang = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblqlkm = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnThungRac = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        jlbtenbang = new javax.swing.JLabel();
        cardgocHoaDon = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_HoaDon = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_HoaDon_HetHan = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Mã Khuyến Mãi");

        jLabel2.setText("Giá Trị");

        jLabel3.setText("Ngày Bắt Đầu");

        jLabel4.setText("Ngày Kết Thúc");

        jLabel5.setText("Giảm Tối Đa");

        jLabel6.setText("Tên Khuyến Mãi");

        buttonGroup1.add(radiovnd);
        radiovnd.setText("VND");

        jLabel8.setText("Hình Thức Áp Dụng");

        buttonGroup1.add(radioPT);
        radioPT.setText("%");

        jLabel9.setText("Loại Giảm Giá");

        buttonGroup2.add(radioDanhMuc);
        radioDanhMuc.setText("Danh Mục");
        radioDanhMuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioDanhMucActionPerformed(evt);
            }
        });

        buttonGroup2.add(radioSanPham);
        radioSanPham.setText("Sản Phẩm");
        radioSanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioSanPhamActionPerformed(evt);
            }
        });

        jpnCardgoc.setLayout(new java.awt.CardLayout());

        jLabel7.setText("Mã Sản Phẩm");

        javax.swing.GroupLayout jpnSPLayout = new javax.swing.GroupLayout(jpnSP);
        jpnSP.setLayout(jpnSPLayout);
        jpnSPLayout.setHorizontalGroup(
            jpnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnSPLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 140, Short.MAX_VALUE))
                    .addComponent(cbbSP, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnSPLayout.setVerticalGroup(
            jpnSPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnSPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnCardgoc.add(jpnSP, "cardSP");

        jLabel10.setText("Mã Danh Mục");

        javax.swing.GroupLayout jpnDMLayout = new javax.swing.GroupLayout(jpnDM);
        jpnDM.setLayout(jpnDMLayout);
        jpnDMLayout.setHorizontalGroup(
            jpnDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDMLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnDMLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 142, Short.MAX_VALUE))
                    .addComponent(cbbDanhMuc, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jpnDMLayout.setVerticalGroup(
            jpnDMLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDMLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbbDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnCardgoc.add(jpnDM, "cardDM");

        buttonGroup3.add(radio_AD_HoaDon);
        radio_AD_HoaDon.setText("Hóa Đơn");
        radio_AD_HoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_AD_HoaDonActionPerformed(evt);
            }
        });

        buttonGroup3.add(radio_AD_SanPham);
        radio_AD_SanPham.setText("Sản Phẩm");
        radio_AD_SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radio_AD_SanPhamActionPerformed(evt);
            }
        });

        jlbadkm.setText("Áp Dụng Giảm Giá");

        jlbhdtt.setText("Tối Thiểu");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(radiovnd, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(radioPT)))
                                .addGap(41, 41, 41)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtGiaTri, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiamToiDa)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jlbadkm, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(radio_AD_SanPham)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(radio_AD_HoaDon)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txthdtoithieu, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(100, 100, 100)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(radioSanPham)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(radioDanhMuc))
                                            .addComponent(jlbhdtt))))
                                .addGap(38, 38, 38)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayBatDau)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayKetThuc)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jpnCardgoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNgayKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtGiamToiDa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radiovnd)
                            .addComponent(radioPT)
                            .addComponent(radioDanhMuc)
                            .addComponent(radioSanPham))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlbadkm)
                            .addComponent(jlbhdtt))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(radio_AD_HoaDon)
                                    .addComponent(radio_AD_SanPham)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(txthdtoithieu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addComponent(jpnCardgoc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpncardGoctbl.setLayout(new java.awt.CardLayout());

        tblhethang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KM", "Tên KM", "Giá Trị", "Giảm Tối Đa", "Ngày BD", "Ngày KT", "Mã SP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblhethang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblhethangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblhethang);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jpncardGoctbl.add(jPanel6, "cardhethan");

        tblqlkm.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KM", "Tên KM", "Giá Trị", "Giảm Tối Đa", "Ngày BD", "Ngày KT", "Mã SP"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblqlkm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblqlkmMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblqlkm);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 947, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 923, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 228, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jpncardGoctbl.add(jPanel4, "cardKM");

        btnThungRac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/poly/icons/DCD.png"))); // NOI18N
        btnThungRac.setText("Hết Hạn");
        btnThungRac.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThungRac.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnThungRac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThungRacActionPerformed(evt);
            }
        });

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnThungRac, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btnThungRac, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jlbtenbang.setFont(new java.awt.Font("Tahoma", 3, 13)); // NOI18N
        jlbtenbang.setForeground(new java.awt.Color(255, 0, 51));
        jlbtenbang.setText("jLabel11");

        cardgocHoaDon.setLayout(new java.awt.CardLayout());

        tbl_HoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KM", "Tên KM", "Giá Trị", "Giảm Tối Đa", "Ngày BD", "Ngày KT", "HDTT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_HoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDonMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_HoaDon);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardgocHoaDon.add(jPanel7, "card_goc");

        tbl_HoaDon_HetHan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã KM", "Tên KM", "Giá Trị", "Giảm Tối Đa", "Ngày BD", "Ngày KT", "HDTT"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_HoaDon_HetHan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_HoaDon_HetHanMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbl_HoaDon_HetHan);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                .addContainerGap())
        );

        cardgocHoaDon.add(jPanel8, "card_phu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpncardGoctbl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jlbtenbang, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(cardgocHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlbtenbang)
                        .addGap(18, 18, 18)
                        .addComponent(jpncardGoctbl, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cardgocHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        ResetForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        if (Validate_QLKhuyenMai()) {
            return;
        }
        boolean hinhthucAD = true;
        boolean LoaiApDung = true;
        String ngaybd = XDate.toString(XDate.toDate(txtNgayBatDau.getText(), "dd/MM/yyyy"), "MM-dd-yyyy");
        String ngaykt = XDate.toString(XDate.toDate(txtNgayKetThuc.getText(), "dd/MM/yyyy"), "MM-dd-yyyy");
        if (radioPT.isSelected()) {
            hinhthucAD = false;
        }

        if (radio_AD_HoaDon.isSelected()) {
            LoaiApDung = false;
            kmDao.Update_NoMaSP(new KhuyenMai(
                    Integer.parseInt(txtKhuyenMai.getText()),
                    Double.parseDouble(txtGiamToiDa.getText()),
                    Double.parseDouble(txtGiaTri.getText()),
                    txtTenKhuyenMai.getText(),
                    ngaybd,
                    ngaykt,
                    hinhthucAD,
                    true,
                    true));
            LoadDataToTable_KM_HoaDon();
            return;
        }

        try {
            kmDao.update(new KhuyenMai(
                    Integer.parseInt(txtKhuyenMai.getText()),
                    Integer.parseInt(cbbSP.getSelectedItem().toString()),
                    Double.parseDouble(txtGiamToiDa.getText()),
                    Double.parseDouble(txtGiaTri.getText()),
                    txtTenKhuyenMai.getText(),
                    ngaybd,
                    ngaykt,
                    hinhthucAD,
                    true,
                    true));
            LoadDataToTable_KM();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (Validate_QLKhuyenMai()) {
            return;
        }
        if (!radio_AD_HoaDon.isSelected() & !radio_AD_SanPham.isSelected()) {
            Messeger.alert(this, "Vui Lòng Chọn Khuyến Mãi Áp Dụng Cho Loại Mặt Hàng");
            return;
        }
        ArrayList<String> s = SanPhamDao.ListSp_NoKhuyenMai(false);
        for (int i = 0; i < s.size(); i++) {
            String get = s.get(i);
            if (cbbSP.getSelectedItem().toString().equals(get)) {
                Messeger.alert(this, "Sản Phẩm này Không Hỗ Trợ Giảm Giá");
                return;
            }
        }

        boolean hinhthucAD = true;
        boolean LoaiApDung = true;
        if (radioPT.isSelected()) {
            hinhthucAD = false;
        }

        if (radio_AD_HoaDon.isSelected()) {
            LoaiApDung = false;
        }
        String ngaybd = XDate.toString(XDate.toDate(txtNgayBatDau.getText(), "dd/MM/yyyy"), "MM-dd-yyyy");
        String ngaykt = XDate.toString(XDate.toDate(txtNgayKetThuc.getText(), "dd/MM/yyyy"), "MM-dd-yyyy");

        
        
        if (radio_AD_HoaDon.isSelected()) {

            KhuyenMai km = new KhuyenMai();
            km.setGiamToiDa(Double.parseDouble(txtGiamToiDa.getText()));
            km.setGiaTri(Double.parseDouble(txtGiaTri.getText()));
            km.setHDToiThieu(Double.parseDouble(txthdtoithieu.getText()));
            km.setTenKM(txtTenKhuyenMai.getText());
            km.setNgayBD(ngaybd);
            km.setNgayKT(ngaykt);
            km.setHinhThucAD(hinhthucAD);
            km.setLoaiKM(LoaiApDung);
            try {
                kmDao.Insert_NoMaSp(km);
                LoadDataToTable_KM_HoaDon();
                return;
            } catch (Exception ex) {
                Logger.getLogger(QL_KhuyenMaiJDiaLog.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        try {
            kmDao.insert(new KhuyenMai(
                    Integer.parseInt(cbbSP.getSelectedItem().toString()),
                    Double.parseDouble(txtGiamToiDa.getText()),
                    Double.parseDouble(txtGiaTri.getText()),
                    txtTenKhuyenMai.getText(),
                    ngaybd,
                    ngaykt,
                    hinhthucAD,
                    LoaiApDung));
            LoadDataToTable_KM();
            ResetForm();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        boolean hinhthucAD = true;
        if (radioPT.isSelected()) {
            hinhthucAD = false;
        }

        try {
            kmDao.delete(txtKhuyenMai.getText());
            LoadDataToTable_KM();
            LoadDataToTable_KM_HoaDon();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void radioSanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioSanPhamActionPerformed
        if (radioSanPham.isSelected()) {
            card_radio.show(jpnCardgoc, "cardSP");
        }
    }//GEN-LAST:event_radioSanPhamActionPerformed

    private void radioDanhMucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioDanhMucActionPerformed
        if (radioDanhMuc.isSelected()) {
            card_radio.show(jpnCardgoc, "cardDM");
        }
    }//GEN-LAST:event_radioDanhMucActionPerformed

    private void tblqlkmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblqlkmMouseClicked
        int viTri = tblqlkm.getSelectedRow();
        if (viTri < 0) {
            return;
        }

        radio_AD_SanPham.setSelected(true);
        txthdtoithieu.setText("");
        setGiaTriHDTT(false);
        setText(viTri);
        if (tblqlkm.getValueAt(viTri, 2).toString().trim().length() > 3) {
            radiovnd.setSelected(true);
        } else {
            radioPT.setSelected(true);
        }
    }//GEN-LAST:event_tblqlkmMouseClicked

    private void btnThungRacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThungRacActionPerformed
        if (btnThungRac.getText().equalsIgnoreCase("Hết Hạn")) {
            card_tbl.show(jpncardGoctbl, "cardhethan");
            card_tbl_hoadon.show(cardgocHoaDon, "card_phu");
            btnThungRac.setText("Khuyễn Mãi");
            jlbtenbang.setText("Bảng : Danh Sách Khuyến Mại Hết Hạn");
            ResetForm();
            setNut(false);
            LoadDataToTable_hethan();
        } else {
            jlbtenbang.setText("Bảng : Danh Sách Khuyến Mại");
            card_tbl.show(jpncardGoctbl, "cardKM");
            card_tbl_hoadon.show(cardgocHoaDon, "card_goc");
            btnThungRac.setText("Hết Hạn");
            setNut(true);
        }
    }//GEN-LAST:event_btnThungRacActionPerformed

    private void tblhethangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblhethangMouseClicked
        int viTri = tblhethang.getSelectedRow();
        if (viTri < 0) {
            return;
        }
        txtKhuyenMai.setText(String.valueOf(tblhethang.getValueAt(viTri, 0)));
        txtTenKhuyenMai.setText(String.valueOf(tblhethang.getValueAt(viTri, 1)));
        if (String.valueOf(tblhethang.getValueAt(viTri, 2)).length() > 3) {
            txtGiaTri.setText(String.valueOf(tblqlkm.getValueAt(viTri, 2)).replace("đ", ""));
        } else {
            txtGiaTri.setText(String.valueOf(tblhethang.getValueAt(viTri, 2)).replace("%", ""));
        }
        txtGiamToiDa.setText(String.valueOf(tblhethang.getValueAt(viTri, 3)));
        txtNgayBatDau.setText(String.valueOf(tblhethang.getValueAt(viTri, 4)));
        txtNgayKetThuc.setText(String.valueOf(tblhethang.getValueAt(viTri, 5)));
        model_sp.setSelectedItem(String.valueOf(String.valueOf(tblhethang.getValueAt(viTri, 6))));
        txtKhuyenMai.setText("");
    }//GEN-LAST:event_tblhethangMouseClicked

    private void radio_AD_HoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_AD_HoaDonActionPerformed
        setGiaTriHDTT(true);
    }//GEN-LAST:event_radio_AD_HoaDonActionPerformed

    private void radio_AD_SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radio_AD_SanPhamActionPerformed
        setGiaTriHDTT(false);
    }//GEN-LAST:event_radio_AD_SanPhamActionPerformed

    private void tbl_HoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDonMouseClicked
        int viTri = tbl_HoaDon.getSelectedRow();
        if (viTri == -1) {
            return;
        }
        setGiaTriHDTT(true);
        radio_AD_HoaDon.setSelected(true);
        txtKhuyenMai.setText(String.valueOf(tbl_HoaDon.getValueAt(viTri, 0)));
        txtTenKhuyenMai.setText(String.valueOf(tbl_HoaDon.getValueAt(viTri, 1)));
        if (String.valueOf(tbl_HoaDon.getValueAt(viTri, 2)).length() > 3) {
            txtGiaTri.setText(String.valueOf(tbl_HoaDon.getValueAt(viTri, 2)).replace("đ", ""));
        } else {
            txtGiaTri.setText(String.valueOf(tbl_HoaDon.getValueAt(viTri, 2)).replace("%", ""));
        }
        txtGiamToiDa.setText(String.valueOf(tbl_HoaDon.getValueAt(viTri, 3)));
        txtNgayBatDau.setText(String.valueOf(tbl_HoaDon.getValueAt(viTri, 4)));
        txtNgayKetThuc.setText(String.valueOf(tbl_HoaDon.getValueAt(viTri, 5)));
        if (tbl_HoaDon.getValueAt(viTri, 2).toString().trim().length() > 3) {
            radiovnd.setSelected(true);
        } else {
            radioPT.setSelected(true);
        }
        txthdtoithieu.setText(String.valueOf(tbl_HoaDon.getValueAt(viTri, 6)).replace("đ", ""));
    }//GEN-LAST:event_tbl_HoaDonMouseClicked

    private void tbl_HoaDon_HetHanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_HoaDon_HetHanMouseClicked
        int viTri = tbl_HoaDon_HetHan.getSelectedRow();
        if (viTri == -1) {
            return;
        }
        setGiaTriHDTT(true);
        radio_AD_HoaDon.setSelected(true);
        txtKhuyenMai.setText(String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 0)));
        txtTenKhuyenMai.setText(String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 1)));
        if (String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 2)).length() > 3) {
            txtGiaTri.setText(String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 2)).replace("đ", ""));
        } else {
            txtGiaTri.setText(String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 2)).replace("%", ""));
        }
        txtGiamToiDa.setText(String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 3)));
        txtNgayBatDau.setText(String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 4)));
        txtNgayKetThuc.setText(String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 5)));
        if (tbl_HoaDon_HetHan.getValueAt(viTri, 2).toString().trim().length() > 3) {
            radiovnd.setSelected(true);
        } else {
            radioPT.setSelected(true);
        }
        txthdtoithieu.setText(String.valueOf(tbl_HoaDon_HetHan.getValueAt(viTri, 6)).replace("đ", ""));
    }//GEN-LAST:event_tbl_HoaDon_HetHanMouseClicked

    private void setNut(boolean boo) {
        btnMoi.setVisible(boo);
        btnSua.setVisible(boo);
        btnThem.setVisible(boo);
        btnXoa.setVisible(boo);

    }

    private void setGiaTriHDTT(boolean boo) {
        jlbhdtt.setVisible(boo);
        txthdtoithieu.setVisible(boo);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QL_KhuyenMaiJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QL_KhuyenMaiJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QL_KhuyenMaiJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QL_KhuyenMaiJDiaLog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                QL_KhuyenMaiJDiaLog dialog = new QL_KhuyenMaiJDiaLog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void setText(int viTri) {
        txtKhuyenMai.setText(String.valueOf(tblqlkm.getValueAt(viTri, 0)));
        txtTenKhuyenMai.setText(String.valueOf(tblqlkm.getValueAt(viTri, 1)));
        if (String.valueOf(tblqlkm.getValueAt(viTri, 2)).length() > 3) {
            txtGiaTri.setText(String.valueOf(tblqlkm.getValueAt(viTri, 2)).replace("đ", ""));
        } else {
            txtGiaTri.setText(String.valueOf(tblqlkm.getValueAt(viTri, 2)).replace("%", ""));
        }
        txtGiamToiDa.setText(String.valueOf(tblqlkm.getValueAt(viTri, 3)));
        txtNgayBatDau.setText(String.valueOf(tblqlkm.getValueAt(viTri, 4)));
        txtNgayKetThuc.setText(String.valueOf(tblqlkm.getValueAt(viTri, 5)));
        model_sp.setSelectedItem(String.valueOf(String.valueOf(tblqlkm.getValueAt(viTri, 6))));

    }

    private void ResetForm() {
        txtKhuyenMai.setText("");
        txtTenKhuyenMai.setText("");
        txtGiaTri.setText("");
        txtGiamToiDa.setText("");
        txtNgayBatDau.setText("");
        txtNgayKetThuc.setText("");
        radiovnd.setSelected(true);
        radioSanPham.setSelected(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThungRac;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JPanel cardgocHoaDon;
    private javax.swing.JComboBox<String> cbbDanhMuc;
    private javax.swing.JComboBox<String> cbbSP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel jlbadkm;
    private javax.swing.JLabel jlbhdtt;
    private javax.swing.JLabel jlbtenbang;
    private javax.swing.JPanel jpnCardgoc;
    private javax.swing.JPanel jpnDM;
    private javax.swing.JPanel jpnSP;
    private javax.swing.JPanel jpncardGoctbl;
    private javax.swing.JRadioButton radioDanhMuc;
    private javax.swing.JRadioButton radioPT;
    private javax.swing.JRadioButton radioSanPham;
    private javax.swing.JRadioButton radio_AD_HoaDon;
    private javax.swing.JRadioButton radio_AD_SanPham;
    private javax.swing.JRadioButton radiovnd;
    private javax.swing.JTable tbl_HoaDon;
    private javax.swing.JTable tbl_HoaDon_HetHan;
    private javax.swing.JTable tblhethang;
    private javax.swing.JTable tblqlkm;
    private javax.swing.JTextField txtGiaTri;
    private javax.swing.JTextField txtGiamToiDa;
    private javax.swing.JTextField txtKhuyenMai;
    private javax.swing.JTextField txtNgayBatDau;
    private javax.swing.JTextField txtNgayKetThuc;
    private javax.swing.JTextField txtTenKhuyenMai;
    private javax.swing.JTextField txthdtoithieu;
    // End of variables declaration//GEN-END:variables

    private void init() {
        setLocationRelativeTo(null);
        setGiaTriHDTT(false);
        ResetForm();
        kmDao = new KhuyenMaiDAO();
        spDao = new SanPhamDao();
        dmDao = new DanhMucDao();
        model_tbl = (DefaultTableModel) tblqlkm.getModel();
        model_tbl_HetHan = (DefaultTableModel) tblhethang.getModel();
        model_tbl_HoaDon = (DefaultTableModel) tbl_HoaDon.getModel();
        model_tbl_HoaDonHetHan = (DefaultTableModel) tbl_HoaDon_HetHan.getModel();
        model_sp = (DefaultComboBoxModel) cbbSP.getModel();
        model_dm = (DefaultComboBoxModel) cbbDanhMuc.getModel();
        modelcbb_dm = (DefaultComboBoxModel) cbbDanhMuc.getModel();
        modelcbb_sp = (DefaultComboBoxModel) cbbSP.getModel();
        card_radio = (CardLayout) jpnCardgoc.getLayout();
        card_tbl = (CardLayout) jpncardGoctbl.getLayout();
        card_tbl_hoadon = (CardLayout) cardgocHoaDon.getLayout();
        card_radio.show(jpnCardgoc, "cardSP");
        card_tbl.show(jpncardGoctbl, "cardKM");
        card_tbl_hoadon.show(cardgocHoaDon, "card_goc");
        jlbtenbang.setText("Bảng : Danh Sách Khuyến Mại");
        LoadDataToCBBSP();
        LoadDataToCBBDM();
        LoadDataToTable_KM();
        LoadDataToTable_KM_HoaDon();
        txtKhuyenMai.setEnabled(false);
        if (tblqlkm.getRowCount() > 0) {
            setText(0);
        }
    }

    private void LoadDataToTable_KM() {
        model_tbl.setRowCount(0);
        try {
            ArrayList<KhuyenMai> list_km = kmDao.selectAll();
            for (int i = 0; i < list_km.size(); i++) {
                KhuyenMai get = list_km.get(i);
                String ngaybd = XDate.toString(XDate.toDate(get.getNgayBD(), "yyyy-MM-dd"), "dd/MM/yyyy");
                String ngaykt = XDate.toString(XDate.toDate(get.getNgayKT(), "yyyy-MM-dd"), "dd/MM/yyyy");
                if (get.isTrangThai() & get.isLoaiKM()) {
                    String Giatri = String.format("%.0f", get.getGiaTri());
                    if (Giatri.trim().length() <= 3) {
                        Giatri = Giatri + "%";
                    } else {
                        Giatri = Giatri + "đ";
                    }
                    String LoaiKM = "Hóa Đơn";
                    if (get.isLoaiKM()) {
                        LoaiKM = "Sản Phẩm";
                    }
                    Object[] rowData = new Object[]{
                        get.getMaKM(),
                        get.getTenKM(),
                        Giatri,
                        get.getGiamToiDa(),
                        ngaybd,
                        ngaykt,
                        get.getMaSP(),
                        LoaiKM
                    };
                    model_tbl.addRow(rowData);
                }

            }
            Auto_HetHan_KhuyenMai();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void LoadDataToTable_hethan() {
        model_tbl_HetHan.setRowCount(0);
        try {
            ArrayList<KhuyenMai> list_km = kmDao.selectAll();
            for (int i = 0; i < list_km.size(); i++) {
                KhuyenMai get = list_km.get(i);
                String ngaybd = XDate.toString(XDate.toDate(get.getNgayBD(), "yyyy-MM-dd"), "dd/MM/yyyy");
                String ngaykt = XDate.toString(XDate.toDate(get.getNgayKT(), "yyyy-MM-dd"), "dd/MM/yyyy");
                if (!get.isTrangThai() & get.isLoaiKM()) {
                    String magaming = String.format("%.0f", get.getGiaTri());
                    if (magaming.trim().length() <= 3) {
                        magaming = magaming + "%";
                    } else {
                        magaming = magaming + "đ";
                    }
                    Object[] rowData = new Object[]{
                        get.getMaKM(),
                        get.getTenKM(),
                        magaming,
                        get.getGiamToiDa(),
                        ngaybd,
                        ngaykt,
                        get.getMaSP()
                    };
                    model_tbl_HetHan.addRow(rowData);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void LoadDataToCBBSP() {
        model_sp.removeAllElements();
        try {
            ArrayList<SanPham> list_sp = spDao.selectAll();
            for (int i = 0; i < list_sp.size(); i++) {
                SanPham get = list_sp.get(i);
                modelcbb_sp.addElement(get);
            }
        } catch (Exception ex) {
            Logger.getLogger(QL_KhuyenMaiJDiaLog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void LoadDataToCBBDM() {
        model_dm.removeAllElements();
        try {
            ArrayList<DanhMuc> list_dm = dmDao.selectAll();
            for (int i = 0; i < list_dm.size(); i++) {
                DanhMuc get = list_dm.get(i);
                modelcbb_dm.addElement(get);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    private void Auto_HetHan_KhuyenMai() {
        for (int i = 0; i < tblqlkm.getRowCount(); i++) {
            String ngaykt = XDate.toString(XDate.toDate(
                    String.valueOf(tblqlkm.getValueAt(i, 5)), "dd/MM/yyyy"), "yyyy-MM-dd");
            Date date1 = Date.valueOf(java.time.LocalDate.now());
            Date date2 = Date.valueOf(ngaykt);
            String relation;
            if (date1.equals(date2)) {
                relation = "Hai ngày trùng nhau";
            } else if (date1.before(date2)) // Hoặc  else if (date1.after(date2)== false)
            {
                relation = "Trước";
            } else {
                relation = "Sau";
            }
            if (relation.equals("Sau")) {
                try {
                    kmDao.delete(String.valueOf(tblqlkm.getValueAt(i, 0)));
                    LoadDataToTable_KM();
                } catch (Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
    }

    private boolean Validate_QLKhuyenMai() {
        StringBuilder x = new StringBuilder();
        if (XValidate.isEmpty(txtTenKhuyenMai)) {
            x.append("Không Để Trống Tên Khuyến Mại\n");
        } else if (XValidate.isEmpty(txtGiaTri)) {
            x.append("Không Để Trống Giá Trị Khuyến Mại\n");
        } else if (Double.parseDouble(txtGiaTri.getText()) < 0) {
            if (XValidate.focus_Errol(false, txtGiaTri)) {
                x.append("Giá Trị Phải Lớn Hơn 0 \n");
            }
        } else if (XValidate.isNotNumber_Double(txtGiaTri)) {
            x.append("Giá Trị Phải Nhập Số \n");
        } else if (XValidate.isEmpty(txtGiamToiDa)) {
            x.append("Không Để Trống Giảm Giá Tối Đa\n");
        } else if (XValidate.isNotNumber_Double(txtGiamToiDa)) {
            x.append("Giảm Giá Tối Đa Phải Nhập Số\n");
        } else if (XValidate.isEmpty(txtNgayBatDau)) {
            x.append("Không Để Trống Ngày Bắt Đầu Khuyến Mại\n");
        } else if (XValidate.IsNotDate(txtNgayBatDau)) {
            x.append("Vui Lòng Nhập Đúng Định Dạng Ngày Tháng Năm(dd/MM/yyyy)\n");
        } else if (XValidate.isEmpty(txtNgayKetThuc)) {
            x.append("Không Để Trống Ngày Kết Thúc Khuyến Mại\n");
        } else if (XValidate.IsNotDate(txtNgayKetThuc)) {
            x.append("Vui Lòng Nhập Đúng Định Dạng Ngày Tháng Năm(dd/MM/yyyy)\n");
        }else if (radio_AD_HoaDon.isSelected() & XValidate.isEmpty(txthdtoithieu)){
             x.append("Vui Lòng Nhập Giá Trị Tối Thiểu Của Hóa Đơn\n");
        } else if (radiovnd.isSelected() == true & Double.parseDouble(txtGiaTri.getText()) < 10000) {
            if (XValidate.focus_Errol(false, txtGiaTri)) {
                x.append("Giảm Giá Phải Lớn Hơn Hoặc Bằng 10 Ngàn");
            }
        } else if (radioPT.isSelected() == true & Double.parseDouble(txtGiaTri.getText()) > 100 | Double.parseDouble(txtGiaTri.getText()) < 0) {
            if (XValidate.focus_Errol(false, txtGiaTri)) {
                x.append("Giá Trị Khi Giảm Giá Phần Trăm Chỉ Được Nhập Từ 0 đến 100\n");
            }
        }

        if (x.toString().length() > 0) {
            Messeger.alert(this, x.toString());
            return true;
        }

        return false;
    }

    private void LoadDataToTable_KM_HoaDon() {
        model_tbl_HoaDon.setRowCount(0);
        try {
            ArrayList<KhuyenMai> list_km = kmDao.selectAll();
            for (int i = 0; i < list_km.size(); i++) {
                KhuyenMai get = list_km.get(i);
                String ngaybd = XDate.toString(XDate.toDate(get.getNgayBD(), "yyyy-MM-dd"), "dd/MM/yyyy");
                String ngaykt = XDate.toString(XDate.toDate(get.getNgayKT(), "yyyy-MM-dd"), "dd/MM/yyyy");
                if (get.isTrangThai() & !get.isLoaiKM()) {
                    String Giatri = String.format("%.0f", get.getGiaTri());
                    if (Giatri.trim().length() <= 3) {
                        Giatri = Giatri + "%";
                    } else {
                        Giatri = Giatri + "đ";
                    }

                    String GiatriHDTT = String.format("%.0f", get.getHDToiThieu()) + "đ";
                    Object[] rowData = new Object[]{
                        get.getMaKM(),
                        get.getTenKM(),
                        Giatri,
                        get.getGiamToiDa(),
                        ngaybd,
                        ngaykt,
                        GiatriHDTT
                    };
                    model_tbl_HoaDon.addRow(rowData);
                }

            }
            LoadDataToTable_KM_HoaDonHetHan();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }

    private void LoadDataToTable_KM_HoaDonHetHan() {
        model_tbl_HoaDonHetHan.setRowCount(0);
        try {
            ArrayList<KhuyenMai> list_km = kmDao.selectAll();
            for (int i = 0; i < list_km.size(); i++) {
                KhuyenMai get = list_km.get(i);
                String ngaybd = XDate.toString(XDate.toDate(get.getNgayBD(), "yyyy-MM-dd"), "dd/MM/yyyy");
                String ngaykt = XDate.toString(XDate.toDate(get.getNgayKT(), "yyyy-MM-dd"), "dd/MM/yyyy");
                if (!get.isTrangThai() & !get.isLoaiKM()) {
                    String Giatri = String.format("%.0f", get.getGiaTri());
                    if (Giatri.trim().length() <= 3) {
                        Giatri = Giatri + "%";
                    } else {
                        Giatri = Giatri + "đ";
                    }

                    String GiatriHDTT = String.format("%.0f", get.getHDToiThieu()) + "đ";
                    Object[] rowData = new Object[]{
                        get.getMaKM(),
                        get.getTenKM(),
                        Giatri,
                        get.getGiamToiDa(),
                        ngaybd,
                        ngaykt,
                        GiatriHDTT
                    };
                    model_tbl_HoaDonHetHan.addRow(rowData);
                }

            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
}
