/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package poly.gui;


import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import poly.dao.HoaDonDao;
import poly.dao.TTHoaDonDao;
import poly.entity.HoaDon;
import poly.entity.TTHoaDon;
import poly.helper.CustomDatePicker;
import poly.helper.Messeger;
import poly.helper.XDate;

/**
 *
 * @author Phương Linh
 */
public class QLHoaDonJDialog extends javax.swing.JDialog {
    HoaDonDao HDD= new HoaDonDao();
    TTHoaDonDao TTHDD= new TTHoaDonDao();
    DefaultComboBoxModel<TTHoaDon> Combo= new DefaultComboBoxModel<>();
    DefaultTableModel Model= new DefaultTableModel();
    public QLHoaDonJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        Combo= (DefaultComboBoxModel)cbcTrangThai.getModel();
        Model= (DefaultTableModel)tblHoaDon.getModel();
        txtNgayMua.setSettings(CustomDatePicker.customsDatePicker(txtNgayMua, new javax.swing.ImageIcon(getClass().getResource("/poly/icons/calendar.png"))));
        loadDataToCombobox();
        loadDataToTableModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        txtMaHD = new javax.swing.JTextField();
        cbcTrangThai = new javax.swing.JComboBox<>();
        txtMaNV = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        txtNgayMua = new com.github.lgooddatepicker.components.DatePicker();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        txtGiamGia = new javax.swing.JTextField();
        txtNgayGH = new javax.swing.JTextField();
        txtTienShip = new javax.swing.JTextField();
        txtThanhTien = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 658));

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(255, 255, 0)));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(255, 204, 255)));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 250));
        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBackground(new java.awt.Color(255, 204, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(543, 50));

        btnUpdate.setBackground(new java.awt.Color(204, 204, 204));
        btnUpdate.setText("Update");
        btnUpdate.setPreferredSize(new java.awt.Dimension(100, 40));
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel3.add(btnUpdate);

        btnDelete.setBackground(new java.awt.Color(204, 204, 204));
        btnDelete.setText("Delete");
        btnDelete.setPreferredSize(new java.awt.Dimension(100, 40));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setPreferredSize(new java.awt.Dimension(543, 250));
        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel6.setBackground(new java.awt.Color(255, 204, 204));
        jPanel6.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(255, 204, 255));
        jPanel7.setLayout(new java.awt.GridLayout(0, 1));

        jLabel1.setText(" Mã hóa đơn :");
        jPanel7.add(jLabel1);

        jLabel2.setText(" Trạng thái :");
        jPanel7.add(jLabel2);

        jLabel3.setText(" Mã nhân viên :");
        jPanel7.add(jLabel3);

        jLabel4.setText("Mã khách hàng :");
        jPanel7.add(jLabel4);

        jLabel5.setText("Ngày mua :");
        jPanel7.add(jLabel5);

        jPanel6.add(jPanel7, java.awt.BorderLayout.LINE_START);

        jPanel8.setBackground(new java.awt.Color(255, 204, 255));
        jPanel8.setLayout(new java.awt.GridLayout(0, 1));
        jPanel8.add(txtMaHD);

        jPanel8.add(cbcTrangThai);
        jPanel8.add(txtMaNV);
        jPanel8.add(txtMaKH);
        jPanel8.add(txtNgayMua);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setBackground(new java.awt.Color(255, 204, 255));
        jPanel9.setLayout(new java.awt.GridLayout(0, 1));

        jLabel6.setText("  Giảm giá :");
        jPanel9.add(jLabel6);

        jLabel7.setText("  Ngày giao hàng :");
        jPanel9.add(jLabel7);

        jLabel8.setText("  Tiền ship :");
        jPanel9.add(jLabel8);

        jLabel9.setText("  Thành tiền :");
        jPanel9.add(jLabel9);
        jPanel9.add(jLabel10);

        jPanel5.add(jPanel9, java.awt.BorderLayout.LINE_START);

        jPanel10.setBackground(new java.awt.Color(255, 204, 255));
        jPanel10.setLayout(new java.awt.GridLayout(0, 1));
        jPanel10.add(txtGiamGia);
        jPanel10.add(txtNgayGH);
        jPanel10.add(txtTienShip);

        txtThanhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtThanhTienActionPerformed(evt);
            }
        });
        jPanel10.add(txtThanhTien);
        jPanel10.add(jLabel11);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã HD", "Trạng thái", "Mã NV", "Mã KH", "Ngày mua", "Giảm giá", "Ngày GH", "Tiền ship", "Thành tiền"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        jPanel1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtThanhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtThanhTienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtThanhTienActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        if (CheckForm()) {
            return;
        }
        HoaDon HD= new HoaDon();
        TTHoaDon TTHD = new TTHoaDon();
        HD.setMaHD(Integer.parseInt(txtMaHD.getText()));
        TTHD= (TTHoaDon) cbcTrangThai.getSelectedItem();
        HD.setMaTT(TTHD.getMaTT());
        HD.setMaNV(txtMaNV.getText());
        HD.setMaKH(txtMaKH.getText());
        HD.setNgayMua(txtNgayMua.getText());
        HD.setGiamGia(Double.parseDouble(txtGiamGia.getText()));
       // HD.setNgayGiaoHang((txtNgayGH.getText()));
        HD.setTienShip(Double.parseDouble(txtTienShip.getText()));
        HD.setThanhTien(Double.parseDouble(txtThanhTien.getText()));
        try {
            HDD.update(HD);
            Messeger.alert(this, "Cập nhật thành công");
        } catch (Exception ex) {
            Logger.getLogger(QLHoaDonJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        int index = tblHoaDon.getSelectedRow();
        if (index==-1) {
            return;
        }
        txtMaHD.setText(tblHoaDon.getValueAt(index, 0)+"");
        txtMaNV.setText(tblHoaDon.getValueAt(index, 2)+"");
        txtMaKH.setText(tblHoaDon.getValueAt(index, 3)+"");
        txtNgayMua.setText(tblHoaDon.getValueAt(index, 4)+"");
        txtGiamGia.setText(tblHoaDon.getValueAt(index, 5)+"");
        txtNgayGH.setText(tblHoaDon.getValueAt(index, 6)+"");
        txtTienShip.setText(tblHoaDon.getValueAt(index, 7)+"");
        txtThanhTien.setText(tblHoaDon.getValueAt(index, 8)+"");
        TTHoaDon TTHD= new TTHoaDon();
        try {
            TTHD=TTHDD.selectById(String.valueOf( tblHoaDon.getValueAt(index, 1)));
        } catch (Exception ex) {
            Logger.getLogger(QLHoaDonJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        Combo.setSelectedItem(TTHD);
    }//GEN-LAST:event_tblHoaDonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QLHoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QLHoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QLHoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QLHoaDonJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QLHoaDonJDialog dialog = new QLHoaDonJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cbcTrangThai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtGiamGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtNgayGH;
    private com.github.lgooddatepicker.components.DatePicker txtNgayMua;
    private javax.swing.JTextField txtThanhTien;
    private javax.swing.JTextField txtTienShip;
    // End of variables declaration//GEN-END:variables

    private void loadDataToCombobox() {
        this.Combo.removeAllElements();
        List<TTHoaDon> lst = new ArrayList<>();
        try {
            lst=this.TTHDD.selectAll();
            for (TTHoaDon tTHoaDon : lst) {
                Combo.addElement(tTHoaDon);
            }
        } catch (Exception ex) {
            Logger.getLogger(QLHoaDonJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadDataToTableModel() {
        this.Model.setRowCount(0);
        List<HoaDon> listHD= new ArrayList<>();
        try {
            listHD= this.HDD.selectAll();
            for (HoaDon HD : listHD) {
                this.Model.addRow(new Object[]{
                    HD.getMaHD(),
                    HD.getMaTT(),
                    HD.getMaNV(),
                    HD.getMaKH(),
                    HD.getNgayMua(),
                    HD.getGiamGia(),
                    HD.getNgayGiaoHang(),
                    HD.getTienShip(),
                    HD.getThanhTien()
                });
            }
        } catch (Exception ex) {
            Logger.getLogger(QLHoaDonJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private boolean CheckForm() throws HeadlessException {
        StringBuilder sb = new StringBuilder();
        if (txtMaHD.getText().equals("")) {
            sb.append("Bạn không được để trống mã hóa đơn\n");
        }
        if (txtMaNV.getText().equals("")) {
            sb.append("Bạn không được để trống mã nhân viên\n");
        }
        if (txtMaKH.getText().equals("")) {
            sb.append("Bạn không được để trống mã khách hàng\n");
        }
        if (txtNgayMua.getText().equals("")) {
            sb.append("Bạn không được để trống ngày mua\n");
        }
        if (txtGiamGia.getText().equals("")) {
            sb.append("Bạn không được để trống giảm giá\n");
        }
        if (txtNgayGH.getText().equals("")) {
            sb.append("Bạn không được để trống ngày giao hàng\n");
        }
        if (txtTienShip.getText().equals("")) {
            sb.append("Bạn không được để trống tiền ship\n");
        }
        if (txtThanhTien.getText().equals("")) {
            sb.append("Bạn không được để trống thành tiền\n");
        }
        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(this, sb, "Lỗi", JOptionPane.ERROR_MESSAGE);
            return true;
        }
        return false;
        
    }

    
}
