CREATE DATABASE ORANGESYS
GO
USE ORANGESYS
GO
CREATE TABLE VAITRO
(
	MAVAITRO INT IDENTITY(101,1) PRIMARY KEY NOT NULL,
	TENVAITRO NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE TAIKHOAN
(	
	MANV VARCHAR(20) PRIMARY KEY NOT NULL,
	MAVAITRO INT FOREIGN  KEY REFERENCES VAITRO(MAVAITRO) ON DELETE NO ACTION ON UPDATE CASCADE,
	HOTEN NVARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH BIT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SDT VARCHAR(12) NOT NULL,
	DIACHI NVARCHAR(MAX) NOT NULL,
	ANHDAIDIEN NVARCHAR(MAX) NOT NULL,
	NGAYTAO DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE LOAIKHACHHANG
(
	MALOAIKH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENLOAIKH NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE KHACHHANG
(	
	MAKH VARCHAR(20) PRIMARY KEY NOT NULL,
	MALOAIKH INT FOREIGN  KEY REFERENCES LOAIKHACHHANG(MALOAIKH) ON DELETE NO ACTION ON UPDATE CASCADE,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH BIT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SDT VARCHAR(12) NOT NULL,
	DIACHI NVARCHAR(MAX) NOT NULL,
	NGAYTAO DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)


CREATE TABLE DONVITINH
(
	MADVT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENDVT NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE MAUSAC
(
	MAMAU INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENMAU NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE DANHMUC
(
	MADM INT IDENTITY(100,1) PRIMARY KEY NOT NULL,
	TENDANHMUC NVARCHAR(50) NOT NULL,
	NGAYTHEM DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE SIZE
(
	MASIZE VARCHAR(10) PRIMARY KEY NOT NULL,
	LOAISIZE NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE CHATLIEU
(
	MACHATLIEU INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENCHATLIEU NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE SANPHAM
(	
	MASP int identity(1000,1) PRIMARY KEY NOT NULL,
	MADM INT FOREIGN  KEY REFERENCES DANHMUC(MADM) ON DELETE NO ACTION ON UPDATE CASCADE,
	MAVACH VARCHAR(50),
	TENSP NVARCHAR(50) NOT NULL,
	ANHSANPHAM NVARCHAR(MAX),
	GIANHAP MONEY NOT NULL,
	GIABAN MONEY NOT NULL,
	SOLUONG INT NOT NULL,
	NGAYNHAP DATE,
	APDUNGKM BIT DEFAULT 1,
	MADVT INT FOREIGN  KEY REFERENCES DONVITINH(MADVT) ON DELETE NO ACTION ON UPDATE CASCADE,
	MAMAU INT FOREIGN  KEY REFERENCES MAUSAC(MAMAU) ON DELETE NO ACTION ON UPDATE CASCADE,
	MASIZE VARCHAR(10) FOREIGN  KEY REFERENCES SIZE(MASIZE) ON DELETE NO ACTION ON UPDATE CASCADE,
	MACHATLIEU INT FOREIGN  KEY REFERENCES CHATLIEU(MACHATLIEU) ON DELETE NO ACTION ON UPDATE CASCADE,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE KHUYENMAI
(	
	MAKM INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MASP int FOREIGN  KEY REFERENCES SANPHAM(MASP) ON DELETE NO ACTION ON UPDATE CASCADE,
	TENKM NVARCHAR(50) NOT NULL,
	HINHTHUCAD BIT NOT NULL,
	GIATRI DECIMAL NOT NULL,
	GIAMTOIDA MONEY NOT NULL,
	NGAYBATDAU DATE NOT NULL,
	NGAYKETTHUC DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE TT_HOADON
(
	MATT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENTT NVARCHAR(50) NOT NULL
)

CREATE TABLE HOADON
(	
	MAHOADON INT IDENTITY(10001,1) PRIMARY KEY NOT NULL,
	MANV VARCHAR(20) FOREIGN  KEY REFERENCES TAIKHOAN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
	MAKH VARCHAR(20) FOREIGN  KEY REFERENCES KHACHHANG(MAKH) ON DELETE NO ACTION ON UPDATE CASCADE,
	MATT INT FOREIGN  KEY REFERENCES TT_HOADON(MATT) ON DELETE NO ACTION ON UPDATE CASCADE,
	NGAYMUA DATE,
	GIAMGIA MONEY,
	NGAYGIAOHANG DATE,
	TIENSHIP MONEY,
	THANHTIEN MONEY,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE CT_HOADON
(	
	MAHD INT NOT NULL FOREIGN KEY REFERENCES HOADON(MAHOADON) ON DELETE NO ACTION ON UPDATE CASCADE,
	MASP INT NOT NULL FOREIGN KEY REFERENCES SANPHAM(MASP) ON DELETE NO ACTION ON UPDATE CASCADE,
	SOLUONG INT NOT NULL,
	GHICHU NVARCHAR(MAX),
	TRANGTHAI BIT DEFAULT 1
)

--tạo function doanh thu today
IF OBJECT_ID('FNDTTD') IS NOT NULL
	DROP FUNCTION FNDTTD
GO
CREATE FUNCTION FNDTTD (@TODAY DATE)
RETURNS @TONG TABLE (TONGTIEN VARCHAR(20), THANHCONG INT, BIHUY INT)
BEGIN	
	---ĐÊM HD THANH CONG
	DECLARE @THANHCONG INT
	SET @THANHCONG = (SELECT COUNT(MAHOADON) FROM HOADON
				WHERE NGAYMUA = @TODAY AND MATT = 2)
	---ĐÊM HD THANH CONG
	DECLARE @THATBAI INT
	SET @THATBAI = (SELECT COUNT(MAHOADON) FROM HOADON
				WHERE NGAYMUA = @TODAY AND MATT = 3)
	---ĐÊM TONG TIEN
	DECLARE @TONGTIEN MONEY
	SET @TONGTIEN = (SELECT SUM(THANHTIEN) FROM HOADON
				WHERE NGAYMUA = '2022-03-21' AND MATT = 2)
	---HIEN THI
	INSERT @TONG VALUES(IIF(@TONGTIEN <> 0, CONVERT(VARCHAR(20), @TONGTIEN, 1), '0'),@THANHCONG, @THATBAI)
	RETURN
END
GO
SELECT * FROM FNDTTD('2022-03-21')

--tạo thủ tục lưu thống kê DOANH THU TODAY
IF OBJECT_ID('SP_DTNGAY') IS NOT NULL
	DROP PROC SP_DTNGAY
	GO
CREATE PROC SP_DTNGAY(@TODAY DATE)
AS BEGIN
	SELECT
		COUNT(MAHOADON) SOHD,
		COUNT(MATT) AS THANHCONG,
		COUNT(MATT) AS BIHUY,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
	WHERE NGAYMUA = @TODAY
	GROUP BY MATT
END
GO
EXEC SP_DTNGAY '03/21/2022'

--tạo thủ tục lưu thống kê DOANH THU NGAY TRONG THANG
IF OBJECT_ID('SP_DTBYNGAYINMONTH') IS NOT NULL
	DROP PROC SP_DTBYNGAYINMONTH
	GO
CREATE PROC SP_DTBYNGAYINMONTH (@MONTH INT, @YEAR INT)
AS BEGIN
	SELECT
		HD.NGAYMUA NGAYMUA,
		COUNT(HD.MAHOADON) SOHD,							
		SUM(CT.SOLUONG) SOLUONG,
		SUM(CT.SOLUONG * SP.GIABAN) GIABAN,
		SUM(GIAMGIA) GIAMGIA,
		SUM(HD.THANHTIEN) AS DOANHTHU
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE YEAR(NGAYMUA) = @YEAR AND MONTH(NGAYMUA) = @MONTH AND MATT = 2
	GROUP BY NGAYMUA
END
GO
EXEC SP_DTBYNGAYINMONTH 3, 2022

IF OBJECT_ID('SP_DTBYNGAYINMONTH1') IS NOT NULL
	DROP PROC SP_DTBYNGAYINMONTH1
	GO
CREATE PROC SP_DTBYNGAYINMONTH1 (@MONTH INT, @YEAR INT)
AS BEGIN
	SELECT
		HD.NGAYMUA NGAYMUA,
		COUNT(HD.MAHOADON) SOHD,
		SUM(GIAMGIA) GIAMGIA,
		SUM(HD.THANHTIEN) AS DOANHTHU
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE YEAR(NGAYMUA) = @YEAR AND MONTH(NGAYMUA) = @MONTH AND MATT = 2
	GROUP BY NGAYMUA
END
GO
EXEC SP_DTBYNGAYINMONTH1 3, 2022

--tạo thủ tục lưu biểu đồ DOANH THU tháng này
IF OBJECT_ID('SP_CHARTMONTH') IS NOT NULL
	DROP PROC SP_CHARTMONTH
	GO
CREATE PROC SP_CHARTMONTH (@MONTH INT, @YEAR INT)
AS BEGIN
	SELECT
		DAY(HD.NGAYMUA) NGAY,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
	WHERE MONTH(HD.NGAYMUA) = @MONTH AND YEAR(HD.NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY DAY(HD.NGAYMUA)
END
GO
EXEC SP_CHARTMONTH 1, 2022
select * from HOADON

--tạo thủ tục lưu biểu đồ DOANH THU tháng này
IF OBJECT_ID('SP_CHARTYEAR') IS NOT NULL
	DROP PROC SP_CHARTYEAR
	GO
CREATE PROC SP_CHARTYEAR (@YEAR INT)
AS BEGIN
	SELECT
		 MONTH(HD.NGAYMUA) THANG,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
	WHERE YEAR(HD.NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY MONTH(HD.NGAYMUA)
END
GO
EXEC SP_CHARTYEAR 2022


--tạo thủ tục lưu biểu đồ DOANH THU CÁC NĂM
IF OBJECT_ID('SP_CHARTYEARS') IS NOT NULL
	DROP PROC SP_CHARTYEARS
	GO
CREATE PROC SP_CHARTYEARS
AS BEGIN
	SELECT
		 YEAR(HD.NGAYMUA) NAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
	WHERE MATT = 2
	GROUP BY YEAR(HD.NGAYMUA)
END
GO
EXEC SP_CHARTYEARS
--tạo thủ tục lưu thống kê DOANH THU THANG TRONG NAM
IF OBJECT_ID('SP_DTTHANG') IS NOT NULL
	DROP PROC SP_DTTHANG 
	GO
CREATE PROC SP_DTTHANG (@YEAR INT)
AS BEGIN
	SELECT
		CAST(MONTH(HD.NGAYMUA) AS VARCHAR) + '/' + CAST(YEAR(HD.NGAYMUA) AS VARCHAR)THANG,
		COUNT(MAHOADON) SOHD,
		SUM(CT.SOLUONG) SOLUONG,
		SUM(CT.SOLUONG * SP.GIABAN) GIABAN,
		SUM(GIAMGIA) GIAMGIA,
		SUM(CT.SOLUONG * SP.GIABAN) - SUM(GIAMGIA) AS DOANHTHU
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE YEAR(NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY MONTH(NGAYMUA), YEAR(NGAYMUA)
END
GO
EXEC SP_DTTHANG 2022
select * from HOADON

--tạo thủ tục lưu thống kê DOANH THU THEO THANG
IF OBJECT_ID('SP_DTBYTHANG') IS NOT NULL
	DROP PROC SP_DTBYTHANG
	GO
CREATE PROC SP_DTBYTHANG (@MONTH INT, @YEAR INT)
AS BEGIN
	SELECT
		MONTH(HD.NGAYMUA) THANG,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE MONTH(NGAYMUA) = @MONTH AND YEAR(NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY MONTH(NGAYMUA)
END
GO
EXEC SP_DTBYTHANG 3, 2021

--tạo thủ tục lưu thống kê DOANH THU NAM
IF OBJECT_ID('SP_DTNAM') IS NOT NULL
	DROP PROC SP_DTNAM
	GO
CREATE PROC SP_DTNAM
AS BEGIN
	SELECT		
		YEAR(HD.NGAYMUA) NAM,
		COUNT(HD.MAHOADON) SOHD,							
		SUM(CT.SOLUONG) SOLUONG,
		SUM(CT.SOLUONG * SP.GIABAN) GIABAN,
		SUM(GIAMGIA) GIAMGIA,
		SUM(CT.SOLUONG * SP.GIABAN) - SUM(GIAMGIA) AS DOANHTHU
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
		WHERE MATT = 2
	GROUP BY YEAR(HD.NGAYMUA)
END
GO
EXEC SP_DTNAM
SELECT * FROM HOADON
--tạo thủ tục lưu thống kê DOANH THU SP
IF OBJECT_ID('SP_DTSP') IS NOT NULL
	DROP PROC SP_DTSP
	GO
CREATE PROC SP_DTSP
AS BEGIN
	SELECT
		CT.MASP MASP,
		SP.TENSP TENSP,
		SP.SOLUONG CONLAI,
		SUM(CT.SOLUONG) DABAN,
		COUNT(MAHOADON) SOHD,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE MATT = 2
	GROUP BY CT.MASP, SP.TENSP
	ORDER BY SOHD DESC
END
GO
EXEC SP_DTSP

--tạo thủ tục lưu thống kê DOANH THU THEO SP
IF OBJECT_ID('SP_DTBYSP') IS NOT NULL
	DROP PROC SP_DTBYSP
	GO
CREATE PROC SP_DTBYSP (@MASP INT)
AS BEGIN
	SELECT
		CT.MASP,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE CT.MASP = @MASP AND MATT = 2
	GROUP BY CT.MASP
END
GO
EXEC SP_DTBYSP 1002

--tạo thủ tục lưu thống kê DOANH THU DANH MUC
IF OBJECT_ID('SP_DTDM') IS NOT NULL
	DROP PROC SP_DTDM
	GO
CREATE PROC SP_DTDM
AS BEGIN
	SELECT
		DM.MADM,
		COUNT(MAHOADON) SOHD,		
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
		JOIN DANHMUC DM ON DM.MADM = SP.MADM
	WHERE MATT = 2
	GROUP BY DM.MADM
	ORDER BY THANHTIEN DESC
END
GO
EXEC SP_DTDM
SELECT * FROM CT_HOADON
SELECT * FROM SANPHAM
--tạo thủ tục lưu thống kê DOANH THU THEO DANH MUC
IF OBJECT_ID('SP_DTBYDM') IS NOT NULL
	DROP PROC SP_DTBYDM
	GO
CREATE PROC SP_DTBYDM (@MADM INT)
AS BEGIN
	SELECT
		DM.MADM,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
		JOIN DANHMUC DM ON DM.MADM = SP.MADM
	WHERE DM.MADM = @MADM AND MATT = 2
	GROUP BY DM.MADM
END
GO
EXEC SP_DTBYDM 100

--TÌM KIẾM SP
if OBJECT_id('sp_timkiem') is not null	--drop proc sp_timkiemgo--IF OBJECT_ID('SPTIMKIEM') IS NOT NULL
	drop proc sp_timkiem
GO
CREATE PROC sp_timkiem 
		@MASP VARCHAR(50), @MAVACH VARCHAR(50), @TENSP NVARCHAR(50), @TENDANHMUC NVARCHAR(50), @TENMAU NVARCHAR(20),
		@MASIZE VARCHAR(10), @TENCHATLIEU NVARCHAR(50)
AS
		SELECT SANPHAM.MASP, SANPHAM.TENSP, SANPHAM.MAVACH, 
				SANPHAM.GIABAN, SANPHAM.GIANHAP, SANPHAM.SOLUONG,
				DANHMUC.TENDANHMUC, DONVITINH.TENDVT, SANPHAM.MASIZE, 
				MAUSAC.TENMAU, CHATLIEU.TENCHATLIEU, SANPHAM.NGAYNHAP
                  
		FROM     
				  CHATLIEU INNER JOIN
                  SANPHAM ON CHATLIEU.MACHATLIEU = SANPHAM.MACHATLIEU INNER JOIN
                  DANHMUC ON SANPHAM.MADM = DANHMUC.MADM INNER JOIN
                  MAUSAC ON SANPHAM.MAMAU = MAUSAC.MAMAU INNER JOIN
                  SIZE ON SANPHAM.MASIZE = SIZE.MASIZE INNER JOIN
                  DONVITINH ON SANPHAM.MADVT = DONVITINH.MADVT
		WHERE 
				  SANPHAM.MASP like @MASP 
				  or MAVACH like @MAVACH 
				  or SANPHAM.TENSP like @TENSP 
				  or DANHMUC.TENDANHMUC like @TENDANHMUC 
				  and MAUSAC.TENMAU like @TENMAU 
				  and SANPHAM.MASIZE like @MASIZE 
				  and CHATLIEU.TENCHATLIEU like @TENCHATLIEU
SELECT * FROM DANHMUC
SELECT * FROM SANPHAM
SELECT * FROM HOADON
SELECT * FROM CT_HOADON
