CREATE DATABASE ORANGESYS
GO
USE ORANGESYS
GO
CREATE TABLE VAITRO
(
	MAVAITRO INT IDENTITY(101,1) PRIMARY KEY NOT NULL,
	TENVAITRO NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE TAIKHOAN
(	
	MANV VARCHAR(20) PRIMARY KEY NOT NULL,
	MAVAITRO INT FOREIGN  KEY REFERENCES VAITRO(MAVAITRO) ON DELETE NO ACTION ON UPDATE CASCADE,
	HOTEN NVARCHAR(50) NOT NULL,
	MATKHAU VARCHAR(20) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH BIT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SDT VARCHAR(12) NOT NULL,
	DIACHI NVARCHAR(MAX) NOT NULL,
	ANHDAIDIEN NVARCHAR(MAX) NOT NULL,
	NGAYTAO DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE LOAIKHACHHANG
(
	MALOAIKH INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENLOAIKH NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE KHACHHANG
(	
	MAKH VARCHAR(20) PRIMARY KEY NOT NULL,
	MALOAIKH INT FOREIGN  KEY REFERENCES LOAIKHACHHANG(MALOAIKH) ON DELETE NO ACTION ON UPDATE CASCADE,
	HOTEN NVARCHAR(50) NOT NULL,
	NGAYSINH DATE NOT NULL,
	GIOITINH BIT NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	SDT VARCHAR(12) NOT NULL,
	DIACHI NVARCHAR(MAX) NOT NULL,
	NGAYTAO DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)


CREATE TABLE DONVITINH
(
	MADVT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENDVT NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE MAUSAC
(
	MAMAU INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENMAU NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE DANHMUC
(
	MADM INT IDENTITY(100,1) PRIMARY KEY NOT NULL,
	TENDANHMUC NVARCHAR(50) NOT NULL,
	NGAYTHEM DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE SIZE
(
	MASIZE VARCHAR(10) PRIMARY KEY NOT NULL,
	LOAISIZE NVARCHAR(20) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE CHATLIEU
(
	MACHATLIEU INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENCHATLIEU NVARCHAR(50) NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE SANPHAM
(	
	MASP int identity(1000,1) PRIMARY KEY NOT NULL,
	MADM INT FOREIGN  KEY REFERENCES DANHMUC(MADM) ON DELETE NO ACTION ON UPDATE CASCADE,
	MAVACH VARCHAR(50),
	TENSP NVARCHAR(50) NOT NULL,
	ANHSANPHAM NVARCHAR(MAX),
	GIANHAP MONEY NOT NULL,
	GIABAN MONEY NOT NULL,
	SOLUONG INT NOT NULL,
	NGAYNHAP DATE,
	APDUNGKM BIT DEFAULT 1,
	MADVT INT FOREIGN  KEY REFERENCES DONVITINH(MADVT) ON DELETE NO ACTION ON UPDATE CASCADE,
	MAMAU INT FOREIGN  KEY REFERENCES MAUSAC(MAMAU) ON DELETE NO ACTION ON UPDATE CASCADE,
	MASIZE VARCHAR(10) FOREIGN  KEY REFERENCES SIZE(MASIZE) ON DELETE NO ACTION ON UPDATE CASCADE,
	MACHATLIEU INT FOREIGN  KEY REFERENCES CHATLIEU(MACHATLIEU) ON DELETE NO ACTION ON UPDATE CASCADE,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE KHUYENMAI
(	
	MAKM INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	MASP int FOREIGN  KEY REFERENCES SANPHAM(MASP) ON DELETE NO ACTION ON UPDATE CASCADE,
	TENKM NVARCHAR(50) NOT NULL,
	HINHTHUCAD BIT NOT NULL,
	GIATRI DECIMAL NOT NULL,
	GIAMTOIDA MONEY NOT NULL,
	NGAYBATDAU DATE NOT NULL,
	NGAYKETTHUC DATE NOT NULL,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE TT_HOADON
(
	MATT INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	TENTT NVARCHAR(50) NOT NULL
)

CREATE TABLE HOADON
(	
	MAHOADON INT IDENTITY(10001,1) PRIMARY KEY NOT NULL,
	MANV VARCHAR(20) FOREIGN  KEY REFERENCES TAIKHOAN(MANV) ON DELETE NO ACTION ON UPDATE CASCADE,
	MAKH VARCHAR(20) FOREIGN  KEY REFERENCES KHACHHANG(MAKH) ON DELETE NO ACTION ON UPDATE CASCADE,
	MATT INT FOREIGN  KEY REFERENCES TT_HOADON(MATT) ON DELETE NO ACTION ON UPDATE CASCADE,
	NGAYMUA DATE NOT NULL,
	GIAMGIA MONEY,
	NGAYGIAOHANG DATE,
	TIENSHIP MONEY,
	THANHTIEN MONEY,
	TRANGTHAI BIT DEFAULT 1
)

CREATE TABLE CT_HOADON
(	
	MAHD INT NOT NULL FOREIGN KEY REFERENCES HOADON(MAHOADON) ON DELETE NO ACTION ON UPDATE CASCADE,
	MASP INT NOT NULL FOREIGN KEY REFERENCES SANPHAM(MASP) ON DELETE NO ACTION ON UPDATE CASCADE,
	SOLUONG INT NOT NULL,
	GHICHU NVARCHAR(MAX),
	TRANGTHAI BIT DEFAULT 1
)

--tạo thủ tục lưu thống kê DOANH THU NGAY
IF OBJECT_ID('SP_DTNGAY') IS NOT NULL
	DROP PROC SP_DTNGAY
	GO
CREATE PROC SP_DTNGAY
AS BEGIN
	SELECT
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE MATT = 2
	GROUP BY NGAYMUA
END
GO
EXEC SP_DTNGAY

--tạo thủ tục lưu thống kê DOANH THU NGAY HOM NAY
IF OBJECT_ID('SP_DTBYNGAYNOW') IS NOT NULL
	DROP PROC SP_DTBYNGAYNOW
	GO
CREATE PROC SP_DTBYNGAYNOW (@MONTH INT, @YEAR INT)
AS BEGIN
	SELECT
		HD.NGAYMUA NGAYMUA,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE YEAR(NGAYMUA) = @YEAR AND MONTH(NGAYMUA) = @MONTH AND MATT = 2
	GROUP BY NGAYMUA
END
GO
EXEC SP_DTBYNGAYNOW 3, 2022


--tạo thủ tục lưu biểu đồ DOANH THU tháng này
IF OBJECT_ID('SP_BTDT') IS NOT NULL
	DROP PROC SP_BTDT
	GO
CREATE PROC SP_BTDT (@MONTH INT, @YEAR INT)
AS BEGIN
	SELECT
		DAY(HD.NGAYMUA) NGAY,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
	WHERE MONTH(HD.NGAYMUA) = @MONTH AND YEAR(HD.NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY DAY(HD.NGAYMUA)
END
GO
EXEC SP_BTDT 1, 2022
select * from HOADON
--tạo thủ tục lưu thống kê DOANH THU THEO NGAY TRONG THANG
IF OBJECT_ID('SP_DTBYNGAY') IS NOT NULL
	DROP PROC SP_DTBYNGAY
	GO
CREATE PROC SP_DTBYNGAY (@MONTH INT, @YEAR INT)
AS BEGIN
	SELECT
		HD.NGAYMUA,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE MONTH(NGAYMUA) = @MONTH AND YEAR(NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY NGAYMUA
END
GO
EXEC SP_DTBYNGAY 3, 2022

--tạo thủ tục lưu thống kê DOANH THU THANG TRONG NAM
IF OBJECT_ID('SP_DTTHANG') IS NOT NULL
	DROP PROC SP_DTTHANG 
	GO
CREATE PROC SP_DTTHANG (@YEAR INT)
AS BEGIN
	SELECT
		MONTH(HD.NGAYMUA) THANG,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
	WHERE YEAR(NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY MONTH(NGAYMUA), YEAR(NGAYMUA)
END
GO
EXEC SP_DTTHANG 2021
select * from HOADON

--tạo thủ tục lưu thống kê DOANH THU THEO THANG
IF OBJECT_ID('SP_DTBYTHANG') IS NOT NULL
	DROP PROC SP_DTBYTHANG
	GO
CREATE PROC SP_DTBYTHANG (@MONTH INT, @YEAR INT)
AS BEGIN
	SELECT
		MONTH(HD.NGAYMUA) THANG,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE MONTH(NGAYMUA) = @MONTH AND YEAR(NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY MONTH(NGAYMUA)
END
GO
EXEC SP_DTBYTHANG 3, 2021

--tạo thủ tục lưu thống kê DOANH THU NAM
IF OBJECT_ID('SP_DTNAM') IS NOT NULL
	DROP PROC SP_DTNAM
	GO
CREATE PROC SP_DTNAM
AS BEGIN
	SELECT
		YEAR(HD.NGAYMUA) NAM,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
		WHERE MATT = 2
	GROUP BY YEAR(NGAYMUA)
END
GO
EXEC SP_DTNAM

--tạo thủ tục lưu thống kê DOANH THU THEO NAM
IF OBJECT_ID('SP_DTBYNAM') IS NOT NULL
	DROP PROC SP_DTBYNAM
	GO
CREATE PROC SP_DTBYNAM(@YEAR INT)
AS BEGIN
	SELECT
		YEAR(HD.NGAYMUA) NAM,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE YEAR(NGAYMUA) = @YEAR AND MATT = 2
	GROUP BY YEAR(NGAYMUA)
END
GO
EXEC SP_DTBYNAM 2021

--tạo thủ tục lưu thống kê DOANH THU SP
IF OBJECT_ID('SP_DTSP') IS NOT NULL
	DROP PROC SP_DTSP
	GO
CREATE PROC SP_DTSP
AS BEGIN
	SELECT
		CT.MASP,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE MATT = 2
	GROUP BY CT.MASP
END
GO
EXEC SP_DTSP

--tạo thủ tục lưu thống kê DOANH THU THEO SP
IF OBJECT_ID('SP_DTBYSP') IS NOT NULL
	DROP PROC SP_DTBYSP
	GO
CREATE PROC SP_DTBYSP (@MASP INT)
AS BEGIN
	SELECT
		CT.MASP,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
	WHERE CT.MASP = @MASP AND MATT = 2
	GROUP BY CT.MASP
END
GO
EXEC SP_DTBYSP 1002

--tạo thủ tục lưu thống kê DOANH THU DANH MUC
IF OBJECT_ID('SP_DTDM') IS NOT NULL
	DROP PROC SP_DTDM
	GO
CREATE PROC SP_DTDM
AS BEGIN
	SELECT
		DM.MADM,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
		JOIN DANHMUC DM ON DM.MADM = SP.MADM
	WHERE MATT = 2
	GROUP BY DM.MADM
END
GO
EXEC SP_DTDM

--tạo thủ tục lưu thống kê DOANH THU THEO DANH MUC
IF OBJECT_ID('SP_DTBYDM') IS NOT NULL
	DROP PROC SP_DTBYDM
	GO
CREATE PROC SP_DTBYDM (@MADM INT)
AS BEGIN
	SELECT
		DM.MADM,
		COUNT(MAHOADON) SOHD,
		MIN(THANHTIEN) HDTHAPNHAT,
		MAX(THANHTIEN) HDCAONHAT,
		AVG(THANHTIEN) TBHOADON,
		SUM(GIAMGIA) SOTIENGIAM,
		SUM(THANHTIEN) THANHTIEN
	FROM HOADON HD
		JOIN CT_HOADON CT ON CT.MAHD = HD.MAHOADON
		JOIN SANPHAM SP ON SP.MASP = CT.MASP
		JOIN DANHMUC DM ON DM.MADM = SP.MADM
	WHERE DM.MADM = @MADM AND MATT = 2
	GROUP BY DM.MADM
END
GO
EXEC SP_DTBYDM 100
SELECT * FROM DANHMUC
SELECT * FROM SANPHAM
SELECT * FROM HOADON
SELECT * FROM CT_HOADON
