USE ORANGESYS
GO
-- Bảng câu truy vấn dữ liệu

-- Bảng VAITRO
/*
DELETE FROM VAITRO WHERE (MAVAITRO = '1')

UPDATE VAITRO SET TENVAITRO =, TRANGTHAI = WHERE (MAVAITRO = '1')

INSERT INTO VAITRO (MAVAITRO, TENVAITRO, TRANGTHAI) VALUES (,,)

SELECT * FROM   VAITRO

*/

-- Bảng TAIKHOAN
/*
SELECT * FROM TAIKHOAN

SELECT MAVAITRO, HOTEN, MATKHAU, NGAYSINH, GIOITINH, EMAIL, SDT, DIACHI, ANHDAIDIEN, NGAYTAO, TRANGTHAI FROM   TAIKHOAN WHERE (MANV = '1')

DELETE FROM TAIKHOAN WHERE (MANV = '1')

UPDATE TAIKHOAN SET MAVAITRO =, HOTEN =, MATKHAU =, NGAYSINH =, GIOITINH =, EMAIL =, SDT =, DIACHI =, ANHDAIDIEN =, NGAYTAO =, TRANGTHAI = WHERE (MANV = '1')

INSERT INTO TAIKHOAN (MANV, MAVAITRO, HOTEN, MATKHAU, NGAYSINH, GIOITINH, EMAIL, SDT, DIACHI, ANHDAIDIEN, NGAYTAO, TRANGTHAI)
VALUES (,,,,,,,,,,,)
*/

-- Bảng LOAIKHACHHANG